---
title: "Untitled"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
source("R/helper.R")
source("R/anova-1f.R")
source("R/anova-2f.R")
```

```{r}
set.seed(354)
aov <- generate_anova_2f(av.name="Vertraeglichkeit",
                  factor.a.levels = c("Gryffindor","Ravenclaw","Hufflepuff","Slytherin"),
                  factor.a.name = "Haus", factor.b.name = "Geschlecht",
                  factor.b.levels = c("M채nnlich","Weiblich"),
                  obs_min = 0, obs_max = 10, nz = 20, obs_round = 2,noise_sd = 2,
                  cellmeans_by_row = c(70, 85, 
                                       60, 40, 
                                       81, 82,
                                       44, 30) /14 ) 

```


```{r}

cat("Kritischer Wert f체r Haupteffekt des Faktors A - Therapieform:\n")
cat(f_crit(aov,type="A"))
cat("Kritischer Wert f체r Haupteffekt des Faktors B - Diagnose:\n")
cat(f_crit(aov,type="B"))
cat("Kritischer Wert f체r Wechselwirkung:\n")
cat(f_crit(aov,type="AxB"))

result_table(aov)

show_table_of_means(aov)
interaction_plot(aov, gray = TRUE) 

anova_in_R(aov) 
```


# Regression

```{r}
set.seed(3243)
N <- 50
erfahrung <- runif(N,0,40)
schwere <- runif(N,1,10)
qualitaet <- runif(N,1,10)


erfolg <- erfahrung*0.3 - schwere*0.1 + qualitaet*0.7 + rnorm(N,0,5)
erfolg <- erfolg/max(erfolg)*10
  
dat <- data.frame(erfolg, erfahrung, schwere, qualitaet)
dat <- round(dat, 2)
m1 <- lm(erfolg ~ ., data=dat)
summary(m1)
car::vif(m1)
resilienz

write.csv(x = dat, file="klausur-regression-202212.csv",row.names = FALSE,quote=FALSE)
```